String toggleJsonResponseOk = '{"toggles":['
    '{'
    '"name": "prop",'
    '"type": "release",'
    '"value": false'
    '},'
    '{'
    '"name": "prop2",'
    '"type": "release",'
    '"value": true'
    '},'
    '{'
    '"name": "prop3",'
    '"type": "context",'
    '"conditions": [{'
      '"field": "username",'
      '"value": "user2",'
      '"operation": "eq"'
    '}]},'
    '{'
    '"name": "prop4",'
    '"type": "release",'
    '"value": true'
    '}]}';

String toggleJsonEmptyResponseOk = '{"toggles":[]}';